name:                do-notation
version:             0.1.0.0
github:              "jahaynes/do-notation"
license:             BSD3
author:              "John Haynes"
maintainer:          "john.andrew.haynes@gmail.com"
copyright:           "2022 John Haynes"

extra-source-files:
- README.md
- CHANGELOG.md

description: A self-hosted task tracker

dependencies:
- aeson
- base
- binary
- bytestring
- cookie
- cql
- cql-io
- cryptonite
- deepseq
- jwt
- memory
- network
- safe
- safe-exceptions
- servant-server
- split
- sqlite-simple
- stm
- text
- time
- transformers
- uuid
- vector
- vector-algorithms
- warp

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  do-notation:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
